### ISSUE TITLE
State of this module?

### ISSUE THREAD

**Issue by brycefisher** [mweagle/circuit-breaker#2]
Hi @mweagle !

This module seems awesome, but I noticed that the last commit was roughly 3 years ago. Is this module still being maintained? Thanks!

**Comment by mweagle** [comment]
Hi @brycefisher  - not really, I'm happy to accept PRs or transfer ownership if you like.  LMK.

**Comment by brycefisher** [comment]
Cool! Thanks for the info. I'll open an issue if I feel ready to build on this. Thanks for making this public!
